### ISSUE TITLE
the question of download the CSRL_dataset

### ISSUE THREAD

**Issue by kelikeli** [hahahawu/CSAGN#1]
![image](https://user-images.githubusercontent.com/34790058/156878695-840bca49-cd4e-430b-bec4-02b4b9b65373.png)

![image](https://user-images.githubusercontent.com/34790058/156878736-f517cc2e-5eba-452c-a863-c7c83396b285.png)

I can't get 'model_data/duconv.train.data'(.data).
But, when I go to "https://github.com/syxu828/CSRL_dataset" and find the .csrl

**Comment by kelikeli** [comment]
![image](https://user-images.githubusercontent.com/34790058/156881530-880a2d53-914a-44d1-a292-187f3735c2a1.png)

So, I changed the code here, is this correct?

**Comment by hahahawu** [comment]
Yes. It is right.

**Comment by kelikeli** [comment]
> Yes. It is right.

Is it correct to run the command like this ”python train.py CSAGN -batch_size 8  -intra_loss -inter_loss“?

In this command:”python train.py MODEL_NAME -batch_size 128 -bert_version BERT_MODEL -intra_loss -inter_loss“ , I replaced "MODEL_NAME" with "CSAGN"

**Comment by hahahawu** [comment]
> > Yes. It is right.
> 
> Is it correct to run the command like this ”python train.py CSAGN -batch_size 8 -intra_loss -inter_loss“?
> 
> In this command:”python train.py MODEL_NAME -batch_size 128 -bert_version BERT_MODEL -intra_loss -inter_loss“ , I replaced "MODEL_NAME" with "CSAGN"

Yes. Right.

**Comment by kelikeli** [comment]
> 

OK，thanks very much
