### ISSUE TITLE
How to get  newsdialog.test .data and personal.test.data ?

### ISSUE THREAD

**Issue by DuTim** [hahahawu/CSAGN#2]
hello 
 
 You used two additional test data sets in your paper, and I couldn't find the place to get them. How can I get the data of these two parts?
![image](https://user-images.githubusercontent.com/50939742/163507049-dba73d0e-5478-4402-8b45-cdee9c90fb95.png)
thanks !

**Comment by hahahawu** [comment]
> hello
> 
> You used two additional test data sets in your paper, and I couldn't find the place to get them. How can I get the data of these two parts? ![image](https://user-images.githubusercontent.com/50939742/163507049-dba73d0e-5478-4402-8b45-cdee9c90fb95.png) thanks !

We have uploaded the data files. Please find them in model_data dir.
